# Generated by Django 5.0.6 on 2024-06-20 17:16

import tienda.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tamanioaro', models.IntegerField(default=520)),
                ('suspenso', models.CharField(choices=[('DELANTERA', 'DELANTERA'), ('TRASERA', 'TRASERA'), ('DOBLE', 'DOBLE')], default='DELANTERA', max_length=9)),
                ('marco', models.CharField(choices=[('ACERO', 'ACERO'), ('ALUMINIO', 'ALUMINIO'), ('CARBON', 'CARBON')], default='ACERO', max_length=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/productos')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='RUT')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', tienda.models.CustomUserManager()),
            ],
        ),
    ]
