# Generated by Django 5.0.6 on 2024-06-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicicleta',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='bicicleta',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='bicicleta',
            old_name='suspenso',
            new_name='suspension',
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tamanioaro',
            field=models.IntegerField(default=26),
        ),
    ]
