# Generated by Django 5.0.6 on 2024-06-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_description_bicicleta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/productos/'),
        ),
    ]
