# Generated by Django 5.0.6 on 2024-06-25 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_accesorio_servicio_remove_bicicleta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Trek', 'Trek'), ('Specialized', 'Specialized'), ('Giant', 'Giant'), ('Cannondale', 'Cannondale'), ('Scott', 'Scott'), ('Santa Cruz', 'Santa Cruz'), ('Cervélo', 'Cervélo'), ('Bianchi', 'Bianchi'), ('Pinarello', 'Pinarello'), ('Colnago', 'Colnago'), ('Orbea', 'Orbea'), ('Merida', 'Merida'), ('Kona', 'Kona'), ('Yeti', 'Yeti'), ('Canyon', 'Canyon'), ('Cube', 'Cube'), ('Felt', 'Felt'), ('Focus', 'Focus'), ('Wilier Triestina', 'Wilier Triestina'), ('BMC', 'BMC')], default='Trek', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.marca'),
        ),
    ]
