# Generated by Django 5.0.6 on 2024-06-26 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_servicio_descripcion_alter_marca_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='descripcion',
        ),
    ]
