# Generated by Django 5.0.6 on 2024-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='tipoaccesorio',
            field=models.CharField(default='BICICLETA', max_length=100),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='tipobicicleta',
            field=models.CharField(default='MONTAÑA', max_length=100),
        ),
    ]
