# Generated by Django 5.0.6 on 2024-07-03 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_accesorio_tipoaccesorio_bicicleta_tipobicicleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='tipoaccesorio',
            field=models.CharField(choices=[('BICICLETA', 'BICICLETA'), ('CASCOS', 'CASCOS'), ('ROPA', 'ROPA'), ('ZAPATILLAS', 'ZAPATILLAS'), ('LUCES', 'LUCES'), ('CANDADOS', 'CANDADOS'), ('PORTA BICICLETAS', 'PORTA BICICLETAS'), ('OTROS', 'OTROS')], default='BICICLETA', max_length=100),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tipobicicleta',
            field=models.CharField(choices=[('MONTAÑA', 'MONTAÑA'), ('RUTA', 'RUTA'), ('BMX', 'BMX'), ('HIBRIDA', 'HIBRIDA'), ('CICLOCROSS', 'CICLOCROSS'), ('GRAVEL', 'GRAVEL'), ('ENDURO', 'ENDURO'), ('DOWNHILL', 'DOWNHILL')], default='MONTAÑA', max_length=100),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
    ]
